services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build: ./backend
        ports: 
            - "8000:8000"
        depends_on:
            - database

    database:
        image: postgres:18
        environment:
            POSTGRES_USER = gamepanel
            POSTGRES_PASSWORD = gamepanel
            POSTGRES_DB = gamepanel
        volumes:
            - postgres_data:/var/lib/postgresql/database
        ports:
            - "5432:5432"
        
volumes:
    postgres_data
